- shell:
  - command: |
      BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
      ${BASE_DIR}/apps/macos/install.sh
    description: Setting macOS defaults
    quiet: false
    stdout: false
    stderr: true
