- link:
    $HOME/.config/nvim: apps/nvim
- shell:
  - command: |
      BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
      ${BASE_DIR}/apps/nvim/install.sh
    description: Installing and configuring nvim plugins
    quiet: true
    stdout: false
    stdout: true
