# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
export PATH=/Users/amelia/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/amelia/Projects/go:/Users/amelia/go/bin:/usr/local/bin

# fzf
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
