#!/bin/sh

###############################################################################
# Bitly                                                                       #
###############################################################################

export GOPATH=/root/gopath/go1.12.9:/root:/bitly:/bitly/local/go/site-packages/go1.12.9:$GOPATH
export PATH=/bitly/local/bin:/usr/local/bin:/bitly/local/go/bin:$PATH

bitgo=/etc/profile.d/go.sh
if [ -f "$bitgo" ]; then
    source $bitgo
fi

alias dev="cd ~/Projects/bitlyvm"
alias bitly="cd /bitly/src/github.com/bitly/bitly"
alias mountall="mount_bitly"
alias yorebase="git checkout master && git fetch bitly && git rebase bitly/master && git push -f ameliagapin master"

alias tdev="open_tmux_session"

alias flush_mc='echo '\''flush_all'\'' | nc localhost 11211'
alias fix_time='ntpdate -s time.nist.gov'

function mount_bitly() {
    for dir in bitly data ; do
        echo "Ensuring /Volumes/${dir} exists..."
        sudo mkdir -p "/Volumes/${dir}"
        echo "Owning /Volumes/${dir}..."
        sudo chown ${USER}:staff "/Volumes/${dir}"
        echo "Mounting /Volumes/${dir}..."
        sudo mount /Volumes/${dir}
    done
    echo "You should be good to go! maybe"
}

function open_tmux_session() {
    tmux new-session
    tmux selectp -t 1
    tmux send-keys "bitly;vim" C-m
    tmux splitw -v -p 60
    tmux send-keys "bitly" C-m
    tmux selectp -t 2
    tmux splitw -v -p 50
    tmux selectp -t 2
    tmux split -h -p 50
}

function rb() {
    local account="$(git config --get gitOpenPull.baseAccount)"
    git fetch $account || return
    git rebase -i ${account}/master || return
}

function egb() {
    /bitly/src/github.com/bitly/bitly/export.sh ${1}#gobuild
}

function yorebaseit() {
    local account="$(git config --get gitOpenPull.baseAccount)"
    git checkout master || return
    git fetch $account || return
    git fetch ameliagapin || return
    git rebase $account/master || return
    git push -f ameliagapin master || return
    git checkout ${1} || return
    git rebase ameliagapin/${1} || return
    git rebase $account/master || return
    git push -f ameliagapin ${1} || return
}

function testr() {
    ssh -AJ ameliagapin@jdev01.gc4.bitly.net "root@testrunnerssd${1}.bitly.org"
}

function newb() {
    local account="$(git config --get gitOpenPull.baseAccount)"
    git checkout master || return
    git fetch $account || return
    git fetch ameliagapin || return
    git rebase $account/master || return
    git push -f ameliagapin master || return
    git checkout -b ${1} master --no-track
}
