#!/usr/bin/env bash

set -e

BASE_CONFIG="base"
CONFIG_SUFFIX=".yaml"

META_DIR="meta"
CONFIG_DIR="configs"
PROFILES_DIR="profiles"

DOTBOT_DIR="dotbot/dotbot"
DOTBOT_BIN="bin/dotbot"
DOTBOT_PLUGIN_DIR="dotbot"

# make $BASE_DIR available to commands
export BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASE_DIR}"
git submodule update --init --recursive

for config in ${@}; do
    echo "Installing ${config}"

    # create temporary file
    configFile="$(mktemp)"
    suffix="-sudo"
    echo -e "$(<"${BASE_DIR}/${META_DIR}/${BASE_CONFIG}${CONFIG_SUFFIX}")\n$(<"${BASE_DIR}/${META_DIR}/${CONFIG_DIR}/${config%"$suffix"}${CONFIG_SUFFIX}")" > "$configFile"

    cmd=("${BASE_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" \
        --plugin-dir "${DOTBOT_PLUGIN_DIR}/dotbot-pip" \
        --plugin-dir "${DOTBOT_PLUGIN_DIR}/dotbot-yarn" \
        --plugin-dir "${DOTBOT_PLUGIN_DIR}/dotbot-brewfile" \
        -d "${BASE_DIR}" -c "$configFile")

    if [[ $config == *"sudo"* ]]; then
        cmd=(sudo "${cmd[@]}")
    fi

    "${cmd[@]}"
    rm -f "$configFile"
done

cd "${BASE_DIR}"

echo "Restart your terminal..."
