# Installed by `./dots homebrew` (brew bundle). Keep it grouped so it stays
# easy to prune.

# --- taps (only what homebrew-core doesn't carry) ---
tap "go-swagger/go-swagger"
tap "qmk/qmk"
tap "osx-cross/arm"   # qmk toolchain
tap "osx-cross/avr"   # qmk toolchain
tap "abue-ammar/tinycast"

# --- shell ---
brew "bash"
brew "zsh"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "coreutils"
brew "findutils"
brew "tmux"
brew "mosh"
brew "navi"

# --- editors ---
brew "neovim"
brew "vim"
brew "tree-sitter-cli"
brew "lua-language-server"
brew "luarocks"

# --- git ---
brew "git"
brew "git-delta"
brew "git-extras"
brew "git-quick-stats"
brew "gh"
brew "lazygit"
brew "gitui"
brew "tig"
brew "diffnav"
brew "pre-commit"

# --- search / files / text ---
brew "ripgrep"
brew "the_silver_searcher"
brew "ack"
brew "fzf"
brew "peco"
brew "fpp"
brew "bat"
brew "highlight"
brew "tree"
brew "lf"
brew "lnav"
brew "jq"
brew "jo"
brew "yq"
brew "fx"
brew "dust"
brew "duf"

# --- system / network ---
brew "htop"
brew "glances"
brew "ctop"
brew "neofetch"
brew "wget"
brew "httpie"
brew "hey"
brew "nmap"
brew "mas"
brew "duti"   # default apps by UTI, used by ./dots macos

# --- build tools & libraries ---
brew "cmake"
brew "autoconf"
brew "automake"
brew "glib"
brew "libevent"
brew "graphviz"
brew "imagemagick"
brew "gifsicle"

# --- languages ---
brew "go"
brew "node", link: false
brew "nvm"
brew "yarn"
brew "pnpm"
brew "python3"
brew "uv"

# --- go / protobuf toolchain ---
brew "golangci-lint"
brew "golangci-lint-langserver"
brew "staticcheck"
brew "mockery"
brew "gomplate"
brew "buf"
brew "protobuf"
brew "grpc"
brew "go-task"
brew "go-swagger/go-swagger/go-swagger"

# --- kubernetes / cloud / containers ---
brew "kubernetes-cli"
brew "kubectx"
brew "k9s"
brew "kaf"
brew "helm"
brew "stern"
brew "awscli"
brew "lazydocker"

# --- databases ---
brew "mysql"
brew "postgresql"
brew "libpq"
brew "redis"
brew "mycli", link: false
brew "pgcli"

# --- keyboard / hardware ---
brew "qmk/qmk/qmk"
brew "ddcctl"

# --- apps ---
cask "alt-tab"
cask "dash"
cask "docker-desktop"
cask "dropbox"
cask "firefox"
cask "font-hack-nerd-font"
cask "ghostty"
cask "github"
cask "google-chrome"
cask "iterm2"
cask "monitorcontrol"
cask "ngrok"
cask "notunes"
cask "openlens"
cask "postman"
cask "qmk-toolbox"
cask "raycast"
cask "slack"
cask "tinycast"
cask "typora"
