# .zshrc

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# set colors
# export TERM="xterm-256color" # This sets up colors properly
export TERM="tmux-256color" # This option allows undercurls to work in neovim

# set shell
export SHELL=$(which zsh)

ZSH_DISABLE_COMPFIX=true

# Do not display symbol for unterminated lines
export PROMPT_EOL_MARK=''

##########
# HISTORY
##########

HISTFILE=$HOME/.zsh_history
HISTSIZE=50000
SAVEHIST=50000

# Immediately append to history file:
setopt INC_APPEND_HISTORY

# Record timestamp in history:
setopt EXTENDED_HISTORY

# Expire duplicate entries first when trimming history:
setopt HIST_EXPIRE_DUPS_FIRST

# Dont record an entry that was just recorded again:
setopt HIST_IGNORE_DUPS

# Delete old recorded entry if new entry is a duplicate:
setopt HIST_IGNORE_ALL_DUPS

# Do not display a line previously found:
setopt HIST_FIND_NO_DUPS

# Dont record an entry starting with a space:
setopt HIST_IGNORE_SPACE

# Dont write duplicate entries in the history file:
setopt HIST_SAVE_NO_DUPS

# Share history between all sessions:
setopt SHARE_HISTORY

# Execute commands using history (e.g.: using !$) immediatel:
unsetopt HIST_VERIFY


# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
#
# https://github.com/denysdovhan/spaceship-prompt/blob/master/docs/Options.md
ZSH_THEME="spaceship"

# Spaceship settings
# https://github.com/denysdovhan/spaceship-prompt/blob/master/docs/Options.md
SPACESHIP_PROMPT_ORDER=(
    time
    user
    host
    dir
    kubectl
    aws
    git
    exit_code
    line_sep
    # # vi_mode
    char
)
SPACESHIP_PROMPT_ASYNC=false
SPACESHIP_USER_SHOW="always"
SPACESHIP_HOST_SHOW="always"
SPACESHIP_PROMPT_ADD_NEWLINE="false"
SPACESHIP_PROMPT_SEPARATE_LINE="true"
SPACESHIP_TIME_SHOW="true"
SPACESHIP_TIME_SUFFIX=""
SPACESHIP_USER_PREFIX=" "
SPACESHIP_USER_SUFFIX=""
SPACESHIP_HOST_PREFIX="@"
SPACESHIP_DIR_TRUNC_REPO="false"
SPACESHIP_DIR_TRUNC_PREFIX=".../"
SPACESHIP_GIT_STATUS_PREFIX=""
SPACESHIP_GIT_STATUS_SUFFIX=""
SPACESHIP_GIT_STATUS_MODIFIED="**"
SPACESHIP_GIT_STATUS_UNMERGED="!"
SPACESHIP_GIT_STATUS_UNTRACKED=""
SPACESHIP_GIT_STATUS_ADDED="*"
SPACESHIP_GIT_STATUS_RENAMED=""
SPACESHIP_GIT_STATUS_DELETED=""
SPACESHIP_GIT_STATUS_STASHED=""
SPACESHIP_GIT_STATUS_DIVERGED=""
SPACESHIP_KUBECTL_SHOW="true"
SPACESHIP_KUBECTL_SYMBOL=""
SPACESHIP_KUBECTL_VERSION_SHOW="false"
SPACESHIP_KUBECTL_SUFFIX=""
SPACESHIP_AWS_PREFIX="("
SPACESHIP_AWS_SUFFIX=") "
SPACESHIP_AWS_SYMBOL=""

# Spaceship colors
# https://jonasjacek.github.io/colors/
SPACESHIP_TIME_COLOR="1"
SPACESHIP_USER_COLOR="2"
SPACESHIP_HOST_COLOR="3"
SPACESHIP_DIR_COLOR="5"
SPACESHIP_GIT_BRANCH_COLOR="4"
SPACESHIP_KUBE_CONTEXT_COLOR="6"
SPACESHIP_AWS_COLOR="180"

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS=true

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
    git
    zsh-syntax-highlighting
    zsh-autosuggestions
    # navi
    docker
    macos
    fzf
)


source $ZSH/oh-my-zsh.sh


# Source extra files
for file in ~/.{exports,aliases,functions,1password}; do
	[ -r "$file" ] && [ -f "$file" ] && source "$file" && echo "Sourced $file"
done;
unset file;

fpath=($fpath "/root/.zfunctions")

# fzf - needed for navi to work
 [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Define navi cheatsheet locations. Kind of a hack
export NAVI_PATH="$HOME/.cheatsheets:${_navi_path}/cheats"
if [ -d ~/Projects/backend/docs/cheats ]; then
    export NAVI_PATH="${NAVI_PATH}:$HOME/Projects/backend/docs/cheats"
fi

source <(navi widget zsh)

# nvm
source $(brew --prefix nvm)/nvm.sh

